### ISSUE TITLE
Unsupported model: F@ST 4360AIR

### ISSUE THREAD

**Issue by bajansen** [iMicknl/python-sagemcom-api#5]
I recently acquired the Sagemcom box mentioned in the title of this issue. It is a 4G modem distributed by KPN to improve slow DSL speeds through MPTCP magic.

The device is not configured as an independent modem, though nosing around un the value trees does suggest it technically does support it. Unfortunately the account details I have do not allow to change any of the interesting settings.
The device does return a lot of information on executing `$.xmo.getValuesTree("Device/DeviceInfo");` in the web console, though running the example code from this project's readme returns an error when using any of the encryption methods, without any useful information.

## Model information

| Key                      | Value |
| ------------------------ | ----- |
| Model name               | F@ST 4360AIR |
| Hardware Version         | 1.3 |
| Software Version         | SG4J000094C |

## $.xmo.getValuesTree("Device/DeviceInfo");
```
DeviceInfo:
  APIVersion: ""
  AdditionalHardwareVersion: ""
  AdditionalSoftwareVersion: ""
  BackupSoftwareVersion: "SG4J000070C"
  BackupTimeStamp: "0001-01-01T01:00:00+0100"
  BuildDate: "2020-10-06T20:20:34+0200"
  CLID: ""
  ConfigBackupRestoreEnable: false
  Country: "BE"
  CountryCode: "BE"
  Description: ""
  DeviceCategory: ""
  EventLog: ""
  ExternalFirmwareVersion: "SG4J000094C"
  FirstConnection: true
  FirstUseDate: "2021-01-15T20:46:16+0100"
  FlushDeviceLog: false
  GUIAPIVersion: "GUI v1.10.1"
  GUIFirmwareVersion: ""
  HardwareVersion: "1.3"
  InternalFirmwareVersion: "8c.28.31.6614"
  LastBackupDate: "0001-01-01T01:00:00+0100"
  LastRestoreDate: "0001-01-01T01:00:00+0100"
  Locations: []
  Logging: {LogLevel: "Debug", Syslog: {…}}
  MACAddress: "6C:BA:XX:XX:XX:XX"
  Manufacturer: "SagemCom"
  ManufacturerOUI: "A08E78"
  MemoryStatus: {Total: 227080, Free: 104760}
  ModelName: "SagemcomFast4360_KPN"
  ModelNumber: ""
  NetworkProperties: {MaxTCPWindowSize: 0, TCPImplementation: ""}
  ProcessStatus: {CPUUsage: 0, Processes: Array(0), LoadAverage: {…}}
  Processors: []
  ProductClass: "Fast4360Air"
  ProvisioningCode: ""
  ProxierInfo: {ManufacturerOUI: "", ProductClass: "", SerialNumber: "", ProxyProtocol: ""}
  RebootCount: 2
  RebootStatus: 0
  ResetStatus: 0
  RouterName: "6b70"
  SNMP: false
  SerialNumber: "LK20239MEXXXXXX"
  SimpleLogs: {SystemLog: "", FirewallLog: "", CallLog: ""}
  SoftwareVersion: "SG4J000094C"
  SpecVersion: "1.0"
  SupportedDataModels: (3) [{…}, {…}, {…}]
  TemperatureStatus: {TemperatureSensors: Array(0)}
  UpTime: 190886
  UpdateStatus: 0
  VendorConfigFiles: [{…}]
  VendorLogFiles: []
```
